Create a Lending Marketplace dApp on Polygon
figment-networks/learn-tutorials pull request #269
Opened 2021-10-10 17:13 UTC by Devilla

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).
If you do not follow these guidelines, it might take longer for us to review your tutorial and get it published on Learn.

- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [x] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [x] I've proofread the tutorial for spelling and grammar mistakes.
- [x] I've run a linter & prettifier to format my code blocks.
- [x] I've thoroughly explained the code, with inline code comments and text explanations.
- [x] I've run the tutorial to test it and the code works.

2021-10-31 16:16 UTC, Devilla commented
Yeah, @pyr0gan I was working on it but there's so much code to explain that's why I added a github repo instruction to use the codebase.

2021-10-31 23:36 UTC, pyr0gan commented
I'll review this on Monday, November 1st 👍

2021-11-01 17:28 UTC, pyr0gan commented
My main concern here is that we have gone from too much to not enough. As it stands, this tutorial is barely a tutorial. We haven't really explained anything noteworthy to the reader, aside from cloning the repos and using them. 

Calling in @yash-sharma1 @guillaumegaluz for extra eyes. I'm not quite sure how to explain what needs to be done to make this tutorial fit the learning model we're using.

@Devilla Like I said, I'm happy to help you in explaining the code, but I can't write the tutorial for you.

2021-11-02 08:43 UTC, Devilla commented
Okay, @pyr0gan let me update it. Thanks.

2021-11-04 18:16 UTC, Devilla commented
@pyr0gan I have updated the code what I think It should be in two parts that will make sense and help understanding the codebase.
- The part 1 will be regarding the Lending Marketplace project setup and Smart contracts. 
- Similarly, part 2 will contain User Interface components built with Reactjs.
> This would be Part 1: Lending-dapp setup and Smart contracts explaination

2021-11-04 19:29 UTC, pyr0gan commented
> @pyr0gan I have updated the code what I think It should be in two parts that will make sense and help understanding the codebase.

Excellent, @Devilla! I'll review it tomorrow 🙏

2021-11-08 19:52 UTC, pyr0gan requested changes
Hi @Devilla and @RanaPrince 😄 

Thanks for submitting this tutorial and working to make it a solid resource for learners! There are some important fixes to be made to this tutorial, mainly related to syntax highlighting and the formatting of code blocks. Please have a look at my comments and make the fixes - remember to mark the conversations as resolved so that my next review can proceed quickly. If you have any questions, please tag me so that I get a notification!

2021-11-08 19:52 UTC, pyr0gan commented on network-documentation/matic/tutorials/create-a-lending-marketplace-dapp-on-polygon.md
> +```
\```text

2021-11-08 19:52 UTC, pyr0gan commented on network-documentation/matic/tutorials/create-a-lending-marketplace-dapp-on-polygon.md
> + ```
\```solidity

Remove the space in front of the backticks & fix the indentation of this code block.

2021-11-08 19:52 UTC, pyr0gan commented on network-documentation/matic/tutorials/create-a-lending-marketplace-dapp-on-polygon.md
> +> Compiling .\contracts\LoanProduct.sol
This contract was not mentioned in the tutorial 🤔

2021-11-08 19:52 UTC, pyr0gan commented on network-documentation/matic/tutorials/create-a-lending-marketplace-dapp-on-polygon.md
> +Now, `migrate` the compiled smart contracts:
> Now we can migrate (deploy) the compiled smart contracts to the locally running Truffle development blockchain:

2021-11-08 19:52 UTC, pyr0gan commented on network-documentation/matic/tutorials/create-a-lending-marketplace-dapp-on-polygon.md
> +```
\```text

2021-11-08 19:52 UTC, pyr0gan commented on network-documentation/matic/tutorials/create-a-lending-marketplace-dapp-on-polygon.md
> +```
\```text

Also remember to add a new line before and after all code blocks 😁

2021-11-08 19:52 UTC, pyr0gan commented on network-documentation/matic/tutorials/create-a-lending-marketplace-dapp-on-polygon.md
> +```
\```text

2021-11-08 19:52 UTC, pyr0gan commented on network-documentation/matic/tutorials/create-a-lending-marketplace-dapp-on-polygon.md
> +```
\```text

2021-11-08 19:52 UTC, pyr0gan commented on network-documentation/matic/tutorials/create-a-lending-marketplace-dapp-on-polygon.md
> +Run the app in the browser:
> Run the server to be able to access the application UI in your browser:

2021-11-08 19:52 UTC, pyr0gan commented on network-documentation/matic/tutorials/create-a-lending-marketplace-dapp-on-polygon.md
> +In the metamask supported browser create a [Custom RPC](https://medium.com/stakingbits/setting-up-metamask-for-polygon-matic-network-838058f6d844) in the Networks as follows:
> In the Metamask settings on a supported browser, create a [Custom RPC](https://medium.com/stakingbits/setting-up-metamask-for-polygon-matic-network-838058f6d844) in the Networks as follows:

2021-11-08 19:52 UTC, pyr0gan commented on network-documentation/matic/tutorials/create-a-lending-marketplace-dapp-on-polygon.md
> +```
It might be best to present this information without a code block. It's OK to use plaintext 👍

2021-11-08 19:52 UTC, pyr0gan commented on network-documentation/matic/tutorials/create-a-lending-marketplace-dapp-on-polygon.md
> +If you had any difficulties following this tutorial or simply want to discuss Polygon tech with us you can [**join our community today**](https://community.figment.io/) or [**Join our discord channel
I recommend rewriting this a little bit:

> If you had any difficulties following this tutorial or simply want to discuss Polygon tech with us you can join the Figment Learn [community forums](https://community.figment.io/) or [join our Discord community](https://figment.io/devchat)!

2021-11-08 19:52 UTC, pyr0gan commented on network-documentation/matic/tutorials/create-a-lending-marketplace-dapp-on-polygon.md
> +# About the authors
It's OK to provide a little information about yourselves 😄  Gives the tutorial some extra flavour!

2021-11-13 00:27 UTC, pyr0gan approved these changes

2021-11-16 18:35 UTC, pyr0gan commented
Hi @Devilla,

You will need to update this Pull Request to work with the new directory structure of the repository before it can be merged:

- Move images to the `assets` directory, you can then change all image links to the relative path `../assets/image-filename.png`
- Move the markdown file into the `polygon` directory, so the new path would be `polygon/create-a-lending-marketplace-dapp-on-polygon.md`

2021-11-18 21:16 UTC, pyr0gan commented
@Devilla my sincere apologies, I was wrong about the image links. It is best to use a direct URL format to avoid any broken images. If you could please change the image links to use `https://github.com/figment-networks/learn-tutorials/raw/master/assets/image-filename.png` instead of the relative path, we can be confident that all images will display properly in the tutorial 😅 .

2021-11-18 21:16 UTC, pyr0gan approved these changes

2021-11-18 21:20 UTC, Devilla commented
> @Devilla my sincere apologies, I was wrong about the image links. It is best to use a direct URL format to avoid any broken images. If you could please change the image links to use `https://github.com/figment-networks/learn-tutorials/raw/master/assets/image-filename.png` instead of the relative path, we can be confident that all images will display properly in the tutorial 😅 .

It's okay @pyr0gan I don't think there are any images in this tutorial. Thanks.

2021-11-18 23:49 UTC, merged