Tezos Mint Your Own Fungible Token
figment-networks/learn-tutorials pull request #301
Opened 2021-10-31 20:12 UTC by PriyanshuDangi

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request", make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8) and reviewed the [Sample Tutorial Structure](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d). 

Please confirm the following before submitting your tutorial for review - 

- [ x] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [x ] The title of the Pull Request matches the title of my tutorial.
- [ x] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [ x] I've [proofread the tutorial](https://grammarly.com) for spelling and grammar mistakes.
- [ x] I've run a linter & prettifier to format my code blocks.
- [ x] I've thoroughly explained the code, with inline code comments and text explanations.
- [x ] I've run the tutorial to test it and the code works.

**NOTE**: We cannot review your Pull Request if it does not meet the standard outlined above.

2021-11-05 00:31 UTC, pyr0gan commented
Hi @PriyanshuDangi, thank you for your patience! I will review this tutorial tomorrow - Friday November 5th.

2021-11-08 23:41 UTC, pyr0gan requested changes
Hi @PriyanshuDangi,

Thanks for writing this tutorial! You'll need to have a look at my comments and make the appropriate changes. Remember to mark the conversations as resolved once you've made the changes so I know they're complete. Please tag me in a comment if you have any questions 🙏

2021-11-08 23:41 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-mint-fungible-tokens.md
> +cd into the folder
> Change into the directory created by the `git clone` command:

2021-11-08 23:41 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-mint-fungible-tokens.md
> +And visit localhost:3000 to view the app. There won't be much as of now. So let's build it.
> And visit localhost:3000 to view the app. There is not much as of now, so let's build it.

2021-11-08 23:41 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-mint-fungible-tokens.md
> +- Mint (Form to mint the Tokens)
> - Mint (Form to mint the tokens)

2021-11-08 23:41 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-mint-fungible-tokens.md
> +Now to mint tokens, we need the user to connect his wallet and then sign the mint method. Use the IPFS url of the `token.json` we uploaded above.
> Now to mint tokens, we need the user to connect their wallet and then sign the mint method. Use the IPFS url of the `token.json` we uploaded above.

2021-11-08 23:41 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-mint-fungible-tokens.md
> +For transfer also, we need the user to connect his wallet and sign the transfer method.
> For the transfer function, we need the user to connect their wallet and sign the transfer method.

2021-11-08 23:41 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-mint-fungible-tokens.md
> +And we are exporting mint and transfer functions from the file at the end.
> Remember to export the `mint` and `transfer` functions from the file at the end.

2021-11-08 23:41 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-mint-fungible-tokens.md
> +Now we will set the state.
> Now we will set the initial app state with the React hook `useState`:

2021-11-08 23:41 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-mint-fungible-tokens.md
> +And in the end, we close the Mint function and default export it.
It's a little bit confusing to do it this way. It's better to just include this in the code block above it, then immediately after the code block, say "Remember to export the component as the default export."

2021-11-08 23:41 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-mint-fungible-tokens.md
> +Time for `src/components/transfer/Transfer.jsx` (remove the already present code). It will be mostly the same as Mint page with just slight changes.
> Now to make the Transfer component, in `src/components/transfer/Transfer.jsx` (remove the already present code). It will be mostly the same as the Mint component, with just slight changes. Let's import React, useState and our transfer util first:

2021-11-08 23:41 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-mint-fungible-tokens.md
> +Now we will set the state.
> Now we will set the initial app state with the React hook `useState`:

2021-11-08 23:41 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-mint-fungible-tokens.md
> +In our submit function, we take the address, amount, to from the input fields and then we call the transer util. Here we are only trasfering to one account, but more transfers can be added by adding
> In our `submit` function, we take the address, amount, to from the input fields and then we call the transfer util. Here we are only transferring to one account, but more transfers can be added to the transactions array.

2021-11-08 23:41 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-mint-fungible-tokens.md
> +And in the end, we close the Transfer function and default export it.
See above comment, it's better to have this as a single, complete codeblock and to talk about what's happening after the codeblock.

2021-11-08 23:41 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-mint-fungible-tokens.md
> +Now run in terminal
It's better to be specific as to what the command is doing, for example:

> To start the server so you can view the app in your web browser, run the terminal command:

2021-11-08 23:41 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-mint-fungible-tokens.md
> +Open locahost:3000 in browser and mint a token on `/` and transfer them on `/transfer`.
> Open your browser, and navigate to locahost:3000. You can now mint a token from the default page route `/` and transfer tokens on the `/transfer` route.

2021-11-09 06:42 UTC, PriyanshuDangi commented
Hey @pyr0gan, I have made all the changes suggested
Let me know if there are any more changes required.

2021-11-09 06:53 UTC, PriyanshuDangi commented
Hey @pyr0gan, I have made all the changes suggested.
Let me know if there are any more changes required.

2021-11-10 23:45 UTC, pyr0gan approved these changes
Changes look good! Just one link to fix and then we can merge and publish 😄

2021-11-10 23:45 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-mint-fungible-tokens.md
> +- [git]((https://git-scm.com/downloads)) installed
Too many brackets, which breaks the link. Remove one set of brackets surrounding "https://git-scm.com/downloads" to fix.

2021-11-11 16:37 UTC, PriyanshuDangi commented
I fixed it. Thanks for the review @pyr0gan :)

2021-11-16 01:06 UTC, pyr0gan commented
> I fixed it. Thanks for reviewing @pyr0gan :)

Thanks! We'll get this merged and published this week 🚀

2021-11-16 18:23 UTC, pyr0gan commented
Hi @PriyanshuDangi,

You will need to update this Pull Request to work with the new directory structure of the repository before it can be merged:

- Move images to the `assets` directory, you can then change all image links to the relative path `../assets/image-filename.png`
- Move the markdown file into the `tezos` directory, so the new path would be `tezos/tezos-mint-fungible-tokens.md`

2021-11-17 10:44 UTC, PriyanshuDangi commented
Hey @pyr0gan, I updated it.

2021-11-18 21:12 UTC, pyr0gan commented
> Hey @pyr0gan, I updated it.

Very good, the tutorial is complete and looks good - however I must offer my sincere apologies @PriyanshuDangi, I was wrong about the image links. It is best to use a direct URL format to avoid any broken images. If you could please change the image links to use `https://github.com/figment-networks/learn-tutorials/raw/master/assets/image-filename.png` instead of the relative path, we can be confident that all images will display properly in the tutorial 😅 .

2021-11-18 22:13 UTC, PriyanshuDangi commented
> > Hey @pyr0gan, I updated it.
> 
> Very good, the tutorial is complete and looks good - however I must offer my sincere apologies @PriyanshuDangi, I was wrong about the image links. It is best to use a direct URL format to avoid any broken images. If you could please change the image links to use `https://github.com/figment-networks/learn-tutorials/raw/master/assets/image-filename.png` instead of the relative path, we can be confident that all images will display properly in the tutorial sweat_smile .

@pyr0gan done

2021-11-18 23:56 UTC, merged