A beginner's guide to Blockchain and Polygon
figment-networks/learn-tutorials pull request #303
Opened 2021-11-04 14:07 UTC by rajranjan0608

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request", make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8) and reviewed the [Sample Tutorial Structure](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d). 

Please confirm the following before submitting your tutorial for review - 

- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [x] The title of the Pull Request matches the title of my tutorial.
- [x] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [x] I've [proofread the tutorial](https://grammarly.com) for spelling and grammar mistakes.
- [ ] I've run a linter & prettifier to format my code blocks.
- [ ] I've thoroughly explained the code, with inline code comments and text explanations.
- [ ] I've run the tutorial to test it and the code works.

**NOTE**: We cannot review your Pull Request if it does not meet the standard outlined above.

2021-11-08 23:59 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +# A beginner's guide to Blockchain and Polygon
Hi @rajranjan0608 👋 

Before I review this document, I'd like to point out that there are several changes that will need to be made to the wording before I can approve it. I just want to be clear that my goal is not simply to be critical of the content during my review - I am here to help guide you to as polished and comprehensive an article as possible! I appreciate the work you have put towards writing this article, and I will attempt to keep the changes manageable and clear throughout 🙏.

2021-11-15 23:28 UTC, pyr0gan requested changes
Hi @rajranjan0608 ,

As I mentioned, there are some linguistic fixes to be made here. Overall the content could use a bit more polish and I feel that there's some room to expand on the other scaling technologies that Polygon is working on (Rollups especially).

Have a look at my comments and make the necessary changes. I know you're aiming for a conversational tone, and for most articles that's OK but you do need to keep the writing a little bit tighter when you're explaining technology. There are lots of existing articles and documents out there that you can use for inspiration, and please do so - just don't forget to add a References section and link to any articles that you're quoting or paraphrasing!

If you have any questions or want any help with the language, please don't hesitate to tag me in a comment 👍

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +![](../../../.gitbook/assets/explaining-polygon-3-scaling.png)
Remember to alter the image path, and re-add the image to your pull request in the `assets` subdirectory.

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +Consider the main chain as a congested road, where at a time only 20 vehicles can pass. Now, this leads to long traffic jams, when around 100 vehicles approach.
> Consider the main blockchain as a congested road, where only 20 vehicles at a time can be moving. Obviously, this would lead to long traffic jams, whenever more vehicles approach and try to use the road at the same time.

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +There are two solutions to overcome this issue. Either we can broaden the road so that more vehicles can pass at a time (layer 1 solution), or we can make another broad highway bypassing the road so
> There are two obvious solutions to overcome this issue. Either we can broaden the road so that more vehicles can pass at a time (layer 1 solution), or we can make another broad highway bypassing the road so that this would divert some traffic to the highway (layer 2 solution).

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +* State channels
Can you add some links to further documentation on these topics? It's OK to add the links directly to the text.

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +## How MATIC?
\## What is MATIC?

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +**Matic**, in 2017, came as a layer 2 scaling solution for the Ethereum network. Instead of building a new blockchain from scratch for faster transactions and low fees, Matic thrives to scale the Eth
> In 2017, Matic was created as a layer 2 scaling solution for the Ethereum network. Instead of building a new blockchain from scratch for faster transactions and low fees, Matic exists to scale the Ethereum network itself. New projects can easily connect to the Matic network, and still enjoy the security and decentralization of Ethereum.

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +They have initially focused on the **Plasma chain** framework. These are small branch chains of the main chain, which helps in avoiding congestion on the main network.
> Matic's initial focus was on the **Plasma chain** framework. These are small branch chains of the main chain, which help to avoid congestion on the main network.

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +## A deep dive into MATIC
\## Diving into Matic

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +Plasma chains can be used for specific applications like payments, asset swaps, etc. Polygon uses the hybrid of Plasma and PoS for running arbitrary applications on blockchain in a scalable way.
> Plasma chains can be used for specific applications like payments and asset swaps. Polygon uses a hybrid of Plasma and PoS for running arbitrary applications on the blockchain in a scalable way.

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +In Polygon, the Block producer layer is EVM (Ethereum Virtual Machine) compatible, which means it is capable of running smart contracts written in Solidity or made for Ethereum.
> In Polygon, the Block producer layer is EVM (Ethereum Virtual Machine) compatible, which means it is capable of running smart contracts written in the Solidity programming language.

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +General-purpose applications or smart contracts are deployed in this layer. All transactions happen in this layer and are put into the newly created blocks. Polygon promises the 1 second block creati
> General-purpose applications or smart contracts are deployed in this layer. All transactions happen in this layer and are put into the newly created blocks. Polygon is capable of a 1 second block creation time. Blocks are created by a few nodes selected by the PoS layer.

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +This layer is responsible for submitting regular transaction reports on the main chain. This is necessary to utilize the security and decentralization offered by the Ethereum chain. This layer aggreg
> This layer is responsible for submitting regular transaction reports on the main chain. This is necessary to utilize the security and decentralization offered by the Ethereum chain. This layer aggregates the blocks at regular intervals into a Merkle root. This Merkle root contains the transaction reports of all the blocks in that interval. This Merkle root is then verified by all the nodes in this layer. Once verified, a node selected in this layer publishes the Merkle root to the smart contract layer on the main chain. This is known as **checkpointing**. With this checkpoint mechanism, all transactions on the Polygon chain benefit from Ethereum's security.

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +![](../../../.gitbook/assets/explaining-polygon-4-matic-plasma-pos.png)
As mentioned before, you will need to change the image location and path in the image link.

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +## Rebranding Matic - Polygon
> ## Rebranding Matic into Polygon

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +Polygon is often called the **Ethereum's Internet of Blockchain**. This is so because it aims to connect and scale all the Ethereum compatible blockchain networks just like the internet connects peop
> Polygon is often called **Ethereum's Internet of Blockchains**. This is because Polygon aims to connect and scale all the Ethereum compatible blockchain networks, just like the internet connects people. It strives to make an ecosystem of Ethereum-compatible and scalable blockchains, so that every network can enjoy scalability, security, and decentralization at the same time.

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +> A blockchain is Ethereum compatible if we can run smart contracts written for Ethereum on that blockchain.
> A blockchain is considered Ethereum compatible if it can run smart contracts written for Ethereum, commonly known as EVM compatibility.

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +One of the plans is obviously to connect every Ethereum compatible blockchain to a scalable ecosystem. And other plans are to integrate other scalability solutions like ZK-Rollups, Optimistic Rollups
Can you write more about rollups? This section feels quite thin compared to the others.

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +## Conclusion
This should be a top level heading (H1):

\# Conclusion

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +This article's main aim was to focus on Polygon's technology. But it cannot be understood if you do not know what blockchains are, what problems they are facing, and available solutions. Since Polygo
> This article explained some of Polygon's technology and the difference between Proof of Work and Proof of Stake. Since Polygon seeks to solve the problems faced by contemporary blockchains, it is important to understand those problems first. This would also be useful to investors who want to invest in blockchain technologies but do not understand the highly technical whitepapers, which can often require extensive research.

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +## About the author
This section heading should be H1:

\# About the author

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +I am [Raj Ranjan](https://www.linkedin.com/in/iamrajranjan) and I have written this article. Thank you ;)
You can provide a little bit more information about yourself, surely 😄

2021-11-15 23:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/explaining-polygon-and-blockchain.md
> +I am assuming your pizza isn't delivered yet, and you learned a lot of things about Polygon and blockchain ;)
While I appreciate the pizza metaphor, this feels like the wrong way to close it out. Perhaps try to tie the concepts you brought up in the article together and have the pizza delivery be the conclusion?

Seems raw to just leave people hanging with no pizza 😉

2021-11-16 18:33 UTC, pyr0gan commented
Hi @rajranjan0608,

You will need to update this Pull Request to work with the new directory structure of the repository before it can be merged:

- Move images to the `assets` directory, you can then change all image links to the relative path `../assets/image-filename.png`
- Move the markdown file into the `polygon` directory, so the new path would be `polygon/explaining-polygon-and-blockchain.md`

2021-11-16 20:15 UTC, rajranjan0608 commented
Hey @pyr0gan. Thanks a lot for reviewing. I have made changes as per the review. Please have a look.

2021-11-18 21:14 UTC, pyr0gan commented
> Hey @pyr0gan. Thanks a lot for reviewing. I have made changes as per the review. Please have a look.

Very good, @rajranjan0608! Thank you 😄 I must however offer my sincere apologies, as I was wrong about the image links. It is best to use a direct URL format to avoid any broken images. If you could please change the image links to use `https://github.com/figment-networks/learn-tutorials/raw/master/assets/image-filename.png` instead of the relative path, we can be confident that all images will display properly in the tutorial!

2021-11-18 21:18 UTC, pyr0gan approved these changes

2021-11-19 00:02 UTC, merged