Create an AMM on Polkadot using Ink!
figment-networks/learn-tutorials pull request #334
Opened 2021-12-03 15:09 UTC by realnimish

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request", make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8) and reviewed the [Sample Tutorial Structure](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d). 

Please confirm the following before submitting your tutorial for review - 

- [ x ] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [] The title of the Pull Request matches the title of my tutorial.
- [] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [ ] I've [proofread the tutorial](https://grammarly.com) for spelling and grammar mistakes.
- [ ] I've run a linter & prettifier to format my code blocks.
- [ ] I've thoroughly explained the code, with inline code comments and text explanations.
- [ ] I've run the tutorial to test it and the code works.

**NOTE**: We cannot review your Pull Request if it does not meet the standard outlined above.

2021-12-09 18:36 UTC, pyr0gan requested changes
Hi @SayanKar and @realnimish !

Thanks for this well written and easy to follow tutorial. While there is quite a bit of code, you have done well with breaking it down and explaining both the AMM formula and the functions you're using to swap between tokens and the liquidity pool clearly 🙏 

There are some small issues to fix, please have a look over my comments and remember to mark the conversations as resolved when you make the changes 😄

2021-12-09 18:36 UTC, pyr0gan commented on polkadot/create-an-amm-on-polkadot-using-ink.md
> +* **BoxTemplate** :-
For all of these headings, you can remove the trailing -

> * **BoxTemplate** :

2021-12-09 18:36 UTC, pyr0gan commented on polkadot/create-an-amm-on-polkadot-using-ink.md
> +ABI can be obtained from your ink! project folder at `.../target/ink/metadata.json`
> The ABI can be obtained from your ink! project folder at `/target/ink/metadata.json`

2021-12-10 01:45 UTC, realnimish commented on polkadot/create-an-amm-on-polkadot-using-ink.md
> +/// @param _fees: valid interval -> [0,1000)
Hi @pyr0gan, The given brackets are intentional. Square brackets indicates closed end (inclusive) and open end (exclusive)

2021-12-10 01:58 UTC, SayanKar commented on polkadot/create-an-amm-on-polkadot-using-ink.md
> +Let's see the following code block, and understand how it works
The given section is just a template for developers to get an idea of how to interact with the smart contract from frontend.

2021-12-13 23:39 UTC, pyr0gan approved these changes
Changes look good, thanks gentlemen! I'll put this up on our staging for a final check before merging it this week 👍

2021-12-17 05:39 UTC, merged