Build a Funding DAO on Polygon
figment-networks/learn-tutorials pull request #353
Opened 2021-12-09 07:52 UTC by viral-sangani

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request", make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8) and reviewed the [Sample Tutorial Structure](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d). 

Please confirm the following before submitting your tutorial for review - 

- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [x] The title of the Pull Request matches the title of my tutorial.
- [x] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [x] I've [proofread the tutorial](https://grammarly.com) for spelling and grammar mistakes.
- [x] I've run a linter & prettifier to format my code blocks.
- [x] I've thoroughly explained the code, with inline code comments and text explanations.
- [x] I've run the tutorial to test it and the code works.

**NOTE**: We cannot review your Pull Request if it does not meet the standard outlined above.

2021-12-10 23:33 UTC, pyr0gan requested changes
Hi @viral-sangani,

Please have a look over my comments and make the changes, and remember to mark the conversations as resolved when you're finished so my next review can proceed quickly 🙏 

This is quite a code-heavy tutorial, I think that to get a better look at it before we publish I might add it to our staging site so that I can see how it renders. I will let you make the changes first.

Have a great weekend 😄 !

2021-12-10 23:33 UTC, pyr0gan commented on polygon/build-a-funding-dao-on-polygon.md
> +In the `connect` function we are connecting our dApp with metamask and fetching the account.
> In the `connect` function we are connecting our dApp with MetaMask and fetching the account.

2021-12-10 23:33 UTC, pyr0gan commented on polygon/build-a-funding-dao-on-polygon.md
> +In `createProposal`, we are accepting the title, description, amount, and recipient as argument and calling `createProposal` of contract. `createProposal` is a transaction call as the user has to loc
> In `createProposal`, we are passing the title, description, amount, and recipient as arguments and calling `createProposal` of contract. `createProposal` is a transaction call as the user has to lock 5 MATIC tokens to create a proposal.

2021-12-10 23:33 UTC, pyr0gan commented on polygon/build-a-funding-dao-on-polygon.md
> +In `getProposal` we are fetching only one proposal from the contract by sending the proposal id in the `getProposal` method call. In the `vote` function, we are accepting the proposal id and the bool
> In `getProposal` we are fetching only one proposal from the contract by passing the proposal id as the only argument. In the `vote` function, we are accepting the proposal id and the boolean value for vote button action and calling the `vote` method of the contract. Note that only Stakeholders can call the `vote` method.

2021-12-10 23:33 UTC, pyr0gan commented on polygon/build-a-funding-dao-on-polygon.md
> +The `provideFunds` function is called by stakeholders when the voting period is over and the proposal is accepted. Any stakeholder can call the `provideFunds` and pass in the number of tokens they wa
> The `provideFunds` function is called by Stakeholders when the voting period is over and the proposal is accepted. Any Stakeholder can call `provideFunds` and pass in the number of tokens they want to invest in the project. `releaseFunding` is called when the Stakeholder has provided the requested funds and the DAO is ready to transfer the funds to the receiver's address. Any of the Stakeholders can call `releaseFunding`.

2021-12-10 23:33 UTC, pyr0gan commented on polygon/build-a-funding-dao-on-polygon.md
> +Now that we are done with the business logic of our dApp, let's start the frontend.
> Now that we are done with the business logic of our dApp, let's start with displaying the interface.

2021-12-10 23:33 UTC, pyr0gan commented on polygon/build-a-funding-dao-on-polygon.md
> +`index.tsx` is the entry page for all the users. If the user is new, then we show a box and ask them to transfer MATIC token to become a member or stakeholder. The UI for the same looks something lik
> `index.tsx` is the entry page for all the users. If the user is new, then we show a box and ask them to transfer MATIC tokens to become a Member or Stakeholder. The UI for the same looks something like this -

2021-12-10 23:33 UTC, pyr0gan commented on polygon/build-a-funding-dao-on-polygon.md
> +In `index.tsx` we make sure that if we are loading data from the contract then we show loading status, and if the user has not connected metamask, we ask the user to connect the wallet. On the index
> In `index.tsx` we make sure that if we are loading data from the contract then we show loading status, and if the user has not connected MetaMask, we ask the user to connect their wallet. On the index page, if the user is neither a Stakeholder nor a Member, then we show the user a UI from which he/she can transfer MATIC to treasury and become a Member of the DAO. If the user is already a Member, then we show a list of all the current proposals.

2021-12-10 23:33 UTC, pyr0gan commented on polygon/build-a-funding-dao-on-polygon.md
> +For the non-member, we only show the Home tab, for members we show Create Proposal and Stakeholder Lounge tabs and for stakeholders, we show an additional Investments tab in the navbar.
> For the non-Member, we only show the Home tab, for Members we show Create Proposal and Stakeholder Lounge tabs and for Stakeholders, we show an additional Investments tab in the navbar.

2021-12-10 23:33 UTC, pyr0gan commented on polygon/build-a-funding-dao-on-polygon.md
> +            Add <strong>2 MATIC</strong> to become member and more than 2 MATIC
>             Add <strong>2 MATIC</strong> to become a Member and more than 2 MATIC

2021-12-10 23:33 UTC, pyr0gan commented on polygon/build-a-funding-dao-on-polygon.md
> +            become a stakeholder
> become a Stakeholder

2021-12-10 23:33 UTC, pyr0gan commented on polygon/build-a-funding-dao-on-polygon.md
> +We are using the `CreateMember` component on the index page if the user has not joined the DAO. In this component, we are accepting the amount of MATIC token user wants to give to DAO to become a mem
> We are using the `CreateMember` component on the index page if the user has not joined the DAO. In this component, we are accepting the amount of MATIC token user wants to give to DAO to become a Member/Stakeholder. On the Send button, we are calling the `createStakeholder` method from `dataContext`.

2021-12-10 23:33 UTC, pyr0gan commented on polygon/build-a-funding-dao-on-polygon.md
> +`ProposalList` component shows the list of `ProposalCard` present in the contract. If the user is a stakeholder then, the user can click on the card and get a popup modal to vote on the proposal.
> `ProposalList` component shows the list of `ProposalCard` present in the contract. If the user is a Stakeholder then the user can click on the card and get a popup modal to vote on the proposal.

2021-12-10 23:33 UTC, pyr0gan commented on polygon/build-a-funding-dao-on-polygon.md
> +Before calling the `createProposal` we are making an api call to a Next.js api endpoint and passing the image uploaded by the user as form-data. In the api call, we are uploading the image, convertin
> Before calling the `createProposal` function, we are making an API call to a Next.js API endpoint and passing the image uploaded by the user as form-data. In the API call, we are uploading the image, converting it to base64, and storing the image on **Arweave**, then returning the ID of the object.

2021-12-10 23:33 UTC, pyr0gan commented on polygon/build-a-funding-dao-on-polygon.md
> +Goto [https://faucet.arweave.net/](https://faucet.arweave.net/) and follow all the steps to get the `.json` key and `0.02AR` token in the account. Once you have the key, copy the key to the root dire
> Go to [https://faucet.arweave.net/](https://faucet.arweave.net/) and follow all the steps to get your `.json` key and 0.02 AR tokens in the account. Once you have the key, copy the key to the root directory of the project and rename the file to `arweave-key.json`. Make sure to add `arweave-key.json` into your `.gitignore` file.

2021-12-10 23:33 UTC, pyr0gan commented on polygon/build-a-funding-dao-on-polygon.md
> +Let's create the `upload-image.tsx` file and handle the Arweave calls.
Do you mean `upload-image.ts` ?

2021-12-10 23:33 UTC, pyr0gan commented on polygon/build-a-funding-dao-on-polygon.md
> +    res.json({id: transactionA.id});
You probably want to return the 200 status code as well 😉

2021-12-10 23:33 UTC, pyr0gan commented on polygon/build-a-funding-dao-on-polygon.md
> +The last page of the dApp is Stakeholder Lounge. Here users can see their token delegation to the DAO's treasury and can always delegate more token. Members can delegate more tokens from this page to
> The last page of the dApp is the Stakeholder Lounge. Here users can see their token delegation to the DAO's treasury and can always delegate more tokens. Members can delegate more tokens from this page if they want to become a Stakeholder.

2021-12-10 23:33 UTC, pyr0gan commented on polygon/build-a-funding-dao-on-polygon.md
> +About the Author
Don't forget to make it a heading!

> \# About the Author

2021-12-10 23:33 UTC, pyr0gan commented on polygon/build-a-funding-dao-on-polygon.md
> +
It looks like you're missing a Conclusion heading!

Remember to do a quick recap of what was learned in the tutorial.

2021-12-13 04:04 UTC, viral-sangani commented
@pyr0gan I have made the initial review changes.
I have a doubt, in the Demo GIF link, you asked me to change it to `https://raw.githubusercontent.com/...` from `https://github.com/figment-networks/learn-tutorials/raw/master/assets/...`. Do I have to change this for all the images?

2021-12-13 23:45 UTC, pyr0gan commented
> @pyr0gan I have made the initial review changes. I have a doubt, in the Demo GIF link, you asked me to change it to `https://raw.githubusercontent.com/...` from `https://github.com/figment-networks/learn-tutorials/raw/master/assets/...`. Do I have to change this for all the images?

Yeah, we have found that the github.com links don't work reliably. So we just need to use the raw.githubusercontent.com URL. It's also a good idea to include ?raw=true at the end of the URL, after the filename. This will make sure it uses the correct domain and won't get flagged for hotlinking. Just keep in mind that anything published on learn.figment.io is being served on our domain, but we don't upload images to our server. This is the most reliable way to show the correct images that are included in a merged pull request.

If you paste "https://github.com/figment-networks/learn-tutorials/raw/master/assets/" into your address bar, you'll notice it redirects to "https://github.com/figment-networks/learn-tutorials/tree/master/assets".

2021-12-14 01:10 UTC, viral-sangani commented
Yes, that clears up my doubt. Thanks 😀
I have made the required change.

2021-12-14 11:00 UTC, yash-sharma1 requested changes

2021-12-14 11:00 UTC, yash-sharma1 commented on polygon/build-a-funding-dao-on-polygon.md
> +Congratulation on finishing this tutorial. Thank you for taking the time to complete it. In this tutorial, we have learned how to create a Funding DAO smart contract and a frontend using Next.js for
> Congratulation on finishing this tutorial. Thank you for taking the time to complete it.

Both of these lines almost have a same menaing so just keep "Congratulation on finishing this tutorial." and remove the extra part.

2021-12-15 05:01 UTC, viral-sangani commented on polygon/build-a-funding-dao-on-polygon.md
> +- At the end of the voting period, if the proposal is selected, Stakeholders have an option to provide the requested funds to the Member who made the proposal.
It will be an on-chain process, but stakeholders will have a button to trigger that process event manually.

2021-12-15 14:48 UTC, viral-sangani commented
@yash-sharma1 I have updated the conclusion part as you suggested.

2021-12-15 19:24 UTC, pyr0gan approved these changes

2021-12-17 01:18 UTC, merged