feat: gaming on solana
figment-networks/learn-tutorials pull request #358
Opened 2021-12-17 16:16 UTC by blocksan

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request", make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8) and reviewed the [Sample Tutorial Structure](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d). 

Please confirm the following before submitting your tutorial for review - 

- [ ] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [ ] The title of the Pull Request matches the title of my tutorial.
- [ ] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [ ] I've [proofread the tutorial](https://grammarly.com) for spelling and grammar mistakes.
- [ ] I've run a linter & prettifier to format my code blocks.
- [ ] I've thoroughly explained the code, with inline code comments and text explanations.
- [ ] I've run the tutorial to test it and the code works.

**NOTE**: We cannot review your Pull Request if it does not meet the standard outlined above.

2021-12-22 11:43 UTC, yash-sharma1 commented
Thanks for submitting the tutorial @blocksan I appreciate all the efforts you have put into writing this tutorial. We're going to start the review and will let you know all the changes required before publishing it.

2021-12-22 13:23 UTC, yash-sharma1 requested changes
@blocksan I'm done with the initial review of the tutorial so once you make the requested changes we'll do a once more review of it before the final merge. Also, @pyr0gan can you please give it a review before the final changes? :)

2021-12-22 13:23 UTC, yash-sharma1 commented on solana/gaming-on-solana/gaming-on-solana.md
> +    Check the source code of the game at : https://github.com/solanauniversity/solana-games
Can you please provide the detailed steps to add the code and integrate it with our above work? Currently it's quite confuisng for beginner to figure what's next :)

2021-12-22 13:23 UTC, yash-sharma1 commented on solana/gaming-on-solana/gaming-on-solana.md
> +I am a passionate blockchain engineer, avid thinker who is currently thriving to build multiple products in the Solana Ecosystem.
You should include your name in this section. You can update it to -

This tutorial was written by [Sandeep Ghosh](https://github.com/blocksan). You can find connect with him on [LinkedIn](https://www.linkedin.com/in/ersandy/) & on [Figment Forum](https://community.figment.io).

@blocksan you can join us on Figment Forum & Discord so we can tag you at both the places while announcing the tutorial.

2021-12-22 13:25 UTC, yash-sharma1 commented on solana/gaming-on-solana/gaming-on-solana.md
> +```
I mean like this ⬇️  - 
**```javascript**

2021-12-24 02:18 UTC, pyr0gan requested changes
Hi @blocksan,

There are some significant changes required for this tutorial to be published. Please review my comments and if you have any questions do not hesitate to stage me in a comment reply. The main concerns are the code blocks need to be given a syntax highlighting type (this is clearly outlined in the [sample tutorial](https://www.notion.so/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d)) - There are some flaws in the formatting, especially regarding use of bold text and some HTML tags which need to be cleaned up.

There is also an issue with the amount of code blocks and the related explanation - You will need to either break things down and spend some more time explaining the functions being used, or reduce the amount of code blocks. It is best to create a project repository that users can clone and then only highlight the most important code in the tutorial.

I think one of the largest issues is near the end, line 1852 - You have written a tutorial about games on Solana but there isn't really any game content in the tutorial as it is.

Looking forward to your continued work on this tutorial, I think it has a lot of potential however it still needs some polishing before it's ready to be published 🙏

2021-12-27 05:53 UTC, blocksan commented on solana/gaming-on-solana/gaming-on-solana.md
> +## How to create the NFT on Solana
In either case, @yash-sharma1 and @pyr0gan to resolve the conflict and make it more understandable, I have updated the tutorial with some explanation.

2021-12-27 06:59 UTC, blocksan commented on solana/gaming-on-solana/gaming-on-solana.md
> +* Once you complete the above tutorial then you can build any pay per use platform for the end users.
@pyr0gan with all due respect, when I write I use Grammarly and I didn't get any issue with this line. Please suggest the correct grammar for this.

2021-12-27 07:04 UTC, blocksan commented on solana/gaming-on-solana/gaming-on-solana.md
> +So the prepare the file object of the image, we wrote our custom function which can convert any DOM element to base64 string and then base64 to File object.
@pyr0gan In the first paragraph I tried to explain how metadata will hold the image and in the second paragraph I tried to explain how the base64 image is getting converted from the util function.
Please suggest the best lines.

2021-12-29 06:11 UTC, blocksan commented on solana/gaming-on-solana/gaming-on-solana.md
> +* Assuming app name as "DistributeToken"
The list gets long if we try to expand the folders, hence added the file name with proper formatting.

2021-12-29 06:42 UTC, blocksan commented on solana/gaming-on-solana/gaming-on-solana.md
> +```
This 'preflightCommitment' is an extra detail that I thought to provide to the learner. I am not using this while making this transaction. To make it easy, I am removing this explanation.

2021-12-29 06:53 UTC, blocksan commented on solana/gaming-on-solana/gaming-on-solana.md
> +All the classes which we declared on the top need to be converted to struct format with valid data types like u8 which is expected from the on-chain program.
Done.

2022-01-04 21:38 UTC, pyr0gan commented
@blocksan Have you had the opportunity to work on our feedback? We'd like to keep this tutorial moving and get you paid! 😄

2022-01-05 04:51 UTC, blocksan commented
Hi Rogan,

Yes, I fixed most of the comments except 5 6 points. I am going to work on
them by today or tomorrow.

Thanks & Regards,
Sandeep Ghosh,
Building www.solgames.fun


On Wed, Jan 5, 2022 at 3:08 AM Rogan X ***@***.***> wrote:

> @blocksan <https://github.com/blocksan> Have you had the opportunity to
> work on our feedback? We'd like to keep this tutorial moving and get you
> paid! 😄
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/figment-networks/learn-tutorials/pull/358#issuecomment-1005189651>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACBT5245NPOUIJFNDHO3COLUUNSG5ANCNFSM5KJGRY3Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-01-05 21:58 UTC, blocksan commented on solana/gaming-on-solana/gaming-on-solana.md
> +* preflightCommitment: Every transaction on Solana goes through a process of finalization. The longer the transaction has existed on the blockchain, the less likely it is to get reverted. A transacti
It was not needed, hence removed.

2022-01-05 22:01 UTC, blocksan commented
All the comments are fixed, please go through the changes and let me know.

2022-01-06 09:20 UTC, yash-sharma1 commented on solana/gaming-on-solana.md
> +I am a passionate blockchain engineer, an avid thinker who is currently thriving to build multiple products in the Solana ecosystem.
All looks good to me. Just a small update in the "About The Author" section. In this section we refer to a third person i:e; but here 2nd & 3rd lines refer to the 1st person ("I am a...") so need to update them.

2022-01-06 09:23 UTC, yash-sharma1 commented
@pyr0gan also will give it a final review to see if any changes are required or not and after that we can merge it :) 
Thanks, @blocksan for all the efforts you've put into writing this amazing tutorial, appreciate it.

2022-01-06 09:25 UTC, blocksan commented
@yash-sharma1 Thanks for your kinds words. I fixed your comment for the 1st person.

2022-01-12 14:56 UTC, yash-sharma1 approved these changes

2022-01-12 19:01 UTC, pyr0gan commented on solana/gaming-on-solana.md
> +This tutorial is written by Sandeep Ghosh. You can connect with the author on [LinkedIn](https://www.linkedin.com/in/ersandy/) & [Figment Forum](https://community.figment.io/).
Please link to your Forum user page, not just the Forum main page.

2022-01-12 19:02 UTC, pyr0gan commented on solana/gaming-on-solana.md
> +5. [Metaplex Documenation](https://www.metaplex.com)
Probably better to link directly to the docs site: <https://docs.metaplex.com/>

Documenation -> Documentation

2022-01-12 19:03 UTC, pyr0gan commented on solana/gaming-on-solana.md
> +4. [Solana Terminologies](https://docs.solana.com/terminology)
Terminologies -> Terminology

2022-01-12 19:03 UTC, pyr0gan commented on solana/gaming-on-solana.md
> +3. [SPL Token](https://spl.solana.com/token)
SPL Token Docs

2022-01-12 19:17 UTC, blocksan commented on solana/gaming-on-solana.md
> +   }else if(connectToWallet){
Due to project-specific configuration, I have turned my default Prettier off. Do not worry, will fix the spaces based on your comment.

2022-01-12 19:18 UTC, blocksan commented on solana/gaming-on-solana.md
> +//{ status: true, signature: "transaction signature hash"} in case of failure
nice catch !!!

2022-01-12 19:46 UTC, blocksan commented on solana/gaming-on-solana.md
>     history.push('/stack')
@pyr0gan I totally understand that and I personally faced similar issues in one of the products where I had to forcefully reload the page on-load, but here it works as the history stack is very lean for the current product.

2022-01-12 19:59 UTC, blocksan commented
@pyr0gan Thanks for this extensive review, trust me on this that never saw this level of detailed review. I am glad that I actually wrote this tutorial which helped me to curate my content in a more structured way.
Thanks again and please have one more glance at the fixes I pushed.

2022-01-12 20:28 UTC, pyr0gan approved these changes
Thanks for your work on this tutorial, and attention to detail. We appreciate it! 🚀 

Edit:  As I am going over this tutorial and preparing to publish it, it seems that you have not made it into a complete project. As it is, this is a collection of code snippets that are loosely related. I see at the top of the tutorial you mentioned a directory structure, and some of the code blocks reference filenames, but it is not consistently applied throughout the tutorial.

I will attempt to provide the necessary changes before publishing, so that the tutorial makes sense and provides readers with an actual React app to follow along with.

2022-01-12 20:29 UTC, merged

2022-01-13 00:44 UTC, pyr0gan commented
@blocksan After reviewing it further, I think there are a few points that could be explained further, which would improve the overall flow of the tutorial:

You listed the dapp features:

> Features
>
> The decentralized application (DApp) will include the following features:
>
> 1. Phantom wallet connection
> 2. SOL transaction to a wallet
> 3. Game play (We will be able to pick any open source game and copy the code)
> 4. NFT creation for the game play high score

- There is nowhere in the tutorial that you actually explain how to connect the gameplay component.
- There is also no explanation of how to extract a high score from a game and turn it into an NFT.

I am in the process of making some edits, but I think it would still be a good idea to fully explain what you set out to explain with this tutorial 😄