How to experiment with Election Phragmen pallet
figment-networks/learn-tutorials pull request #363
Opened 2022-01-14 01:28 UTC by kelvinwelter

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request", make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8) and reviewed the [Sample Tutorial Structure](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d). 

Please confirm the following before submitting your tutorial for review - 

- [X] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [X] The title of the Pull Request matches the title of my tutorial.
- [X] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [X] I've [proofread the tutorial](https://grammarly.com) for spelling and grammar mistakes.
- [X] I've run a linter & prettifier to format my code blocks.
- [X] I've thoroughly explained the code, with inline code comments and text explanations.
- [X] I've run the tutorial to test it and the code works.

**NOTE**: We cannot review your Pull Request if it does not meet the standard outlined above.

2022-01-25 10:15 UTC, yash-sharma1 commented
Thanks for the submitting the PR @kelvinwelter I'm glad to see this tutorial coming from you. I'm going to start the review on this now and will let you know if any improvmenets are required. :)

2022-01-25 12:34 UTC, yash-sharma1 requested changes

2022-01-25 12:34 UTC, yash-sharma1 commented on polkadot/how-to-experiment-with-election-phragmen-pallet.md
> +![Election component preview](https://raw.githubusercontent.com/figment-networks/learn-tutorials/master/assets/electionComponentPreview.png?raw=true)
Can you please add a gif/video of working election dApp running on localhost?

2022-01-26 19:11 UTC, kelvinwelter commented
Hey @yash-sharma1, I have made the changes you proposed, can you take a look again? Thanks :)

2022-01-28 05:38 UTC, yash-sharma1 approved these changes

2022-01-28 05:40 UTC, yash-sharma1 commented
Thanks, @kelvinwelter for making all these changes. I'm requesting another review from @pyr0gan before we merge it. Rogan will take review and if all is good we'll merge it.

2022-02-01 22:01 UTC, kelvinwelter commented
Hey @pyr0gan, thanks for your feedback! I fixed the details you pointed out, can you take a look again? 

Just one comment about the file created being `Election.js` and not `Election.jsx`: In the Substrate front-end template, which I use here in the tutorial, all ReactJS files end with `.js` and so I decided to do the same with the new file created during the tutorial. This decision was made to try not to confuse the reader of the tutorial. If you prefer, I can make the change to `Election.jsx`, it's up to you :)

2022-02-07 00:34 UTC, pyr0gan approved these changes

2022-02-07 00:34 UTC, merged