Add tutorial for "create a decentralized kickstarter"
figment-networks/learn-tutorials pull request #364
Opened 2022-01-30 12:56 UTC by hyp3r5pace

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request", make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8) and reviewed the [Sample Tutorial Structure](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d). 

Please confirm the following before submitting your tutorial for review - 

- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [x] The title of the Pull Request matches the title of my tutorial.
- [x] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [x] I've [proofread the tutorial](https://grammarly.com) for spelling and grammar mistakes.
- [x] I've run a linter & prettifier to format my code blocks.
- [x] I've thoroughly explained the code, with inline code comments and text explanations.
- [x] I've run the tutorial to test it and the code works.

**NOTE**: We cannot review your Pull Request if it does not meet the standard outlined above.

2022-02-04 08:22 UTC, yash-sharma1 commented
Hey @hyp3r5pace
Thanks for submitting the tutorial. I'm gonna do the first review of it now and will let you know if any changes are required.

2022-02-04 09:04 UTC, yash-sharma1 requested changes

2022-02-04 09:04 UTC, yash-sharma1 commented on avalanche/create-a-decentralized-kickstarter.md
> +Approve the transaction on Metamask pop-up interface. Once our contract is deployed successfully, make note of the deployed `contract address`.
Here you should include the potentials errors which a learner can face and steps to troubleshoot them, just like if learner not able to deploy it via Remix what should be the error how it can be resolved

2022-02-04 09:04 UTC, yash-sharma1 commented on avalanche/create-a-decentralized-kickstarter.md
> +This tutorial was created by [Soumyajit Deb](https://github.com/hyp3r5pace) and [Sayan Kar](https://github.com/SayanKar). You can reach out to them on [Figment Forum](https://community.figment.io/u/d
Please remove this part which is redirecting to Forum as forum will be deprecated in coming time.

2022-02-08 17:34 UTC, hyp3r5pace commented
@yash-sharma1 We made the changes as requested!

2022-02-15 11:04 UTC, yash-sharma1 approved these changes

2022-02-15 11:07 UTC, yash-sharma1 commented
@SayanKar & @hyp3r5pace Thanks for making all the changes, all looks good to me. Soon @pyr0gan will also take a look at it and will let you know if any changes are required. We'll do a final review before merging the request.

2022-02-15 19:00 UTC, pyr0gan requested changes
Hi @hyp3r5pace and @SayanKar 😄 

Just a few easy fixes here, mostly details like Solidity formatting, a couple of typos and some capitalization & grammar tweaks. Have a look over my review comments and remember to mark the conversations as resolved when you've committed the changes to your branch 🙏

2022-02-15 19:00 UTC, pyr0gan commented on avalanche/create-a-decentralized-kickstarter.md
> +contract crowdfunding {
Solidity contracts are generally named in UpperCamelCase (called CapWords in the [Solidity style guide](https://docs.soliditylang.org/en/latest/style-guide.html#naming-styles)) 😄 

```solidity
contract Crowdfunding {
```

2022-02-15 19:00 UTC, pyr0gan commented on avalanche/create-a-decentralized-kickstarter.md
> +Let's define the structures and enums that are required to define states. We will make two enums **Category**, which can have four values representing the category to which the project belongs, and t
> Let's define the structures and enums that are required for the contract state. We will make two enums: **Category**, which can have four values representing the category to which the project belongs, and **RefundPolicy**, which can have two values.

2022-02-15 19:00 UTC, pyr0gan commented on avalanche/create-a-decentralized-kickstarter.md
> +enum Category{
There should always be a space between the object name and the opening `{`:

```solidity
enum Category {
```
Check the [Solidity style guide](https://docs.soliditylang.org/en/latest/style-guide.html) for more details.

2022-02-15 19:00 UTC, pyr0gan commented on avalanche/create-a-decentralized-kickstarter.md
> +                || projects[_index].amountRaised >= projects[_index].fundingGoal, "Funding goal not reached");
Looks like 12 spaces of indentation here. 4 spaces per level of indentation is preferred 😄 Line the `||` up with the u in "require" on the line above (i.e. - take out 8 spaces from the beginning of this line).

2022-02-15 19:00 UTC, pyr0gan commented on avalanche/create-a-decentralized-kickstarter.md
> +When **REFUNDABLE** project is not able to achieve its funding goal, the contributors can get their refund with the help of `claimRefund` function. `getContributorIndex` is a helper function to retri
Better to replace "he/she has" with "they have" :

> ... if they have contributed, otherwise returns -1.

2022-02-15 19:00 UTC, pyr0gan commented on avalanche/create-a-decentralized-kickstarter.md
> +                && projects[_index].amountRaised < projects[_index].fundingGoal, "Funding goal not reached");
Fix the indentation here, 4 spaces 👍

2022-02-15 19:00 UTC, pyr0gan commented on avalanche/create-a-decentralized-kickstarter.md
> + - **New RPC URL:** [ https://api.avax-test.network/ext/bc/C/rpc]( https://api.avax-test.network/ext/bc/C/rpc)
Remove the spaces in front of the link description & URL here and also on line 335.
It should not really have an effect on the link working, but let's clean up the syntax before we ship 😄 

> As-is:  - **New RPC URL:** \[ https://api.avax-test.network/ext/bc/C/rpc]( https://api.avax-test.network/ext/bc/C/rpc)  
> Fixed:  - **New RPC URL:** \[https://api.avax-test.network/ext/bc/C/rpc](https://api.avax-test.network/ext/bc/C/rpc)

2022-02-15 19:00 UTC, pyr0gan commented on avalanche/create-a-decentralized-kickstarter.md
> +This component renders the profile information of a user. This component has three sections, namely `Ongoing projects` section, `Completed projects` section and `Projects funded` section. The `Ongoin
See the above comment. If quotes don't work, you can also use **bold text** or _italics_ for emphasis! 😄 

i.e. - **Ongoing projects** instead of `Ongoing projects`

2022-02-15 19:00 UTC, pyr0gan commented on avalanche/create-a-decentralized-kickstarter.md
> +Congratulations! We have successfully developed a working decentralized Kickstarter where users can create projects, fund various projects and even claim refunds if possible. As a next step, you can
> Congratulations! We have successfully developed a working decentralized crowdfunding application where users can create projects, fund various projects and even claim refunds if possible. As a next step, you can try adding new features to the dApp, such as royalties for the dApp owner or providing NFTs to the top contributors of a project.

2022-02-15 19:00 UTC, pyr0gan commented on avalanche/create-a-decentralized-kickstarter.md
> +- Check if your account has sufficient balance at [fuji block-explorer](https://cchain.explorer.avax-test.network/). You ca fund your address from the given [faucet](https://faucet.avax-test.network/
> - Check if your account has sufficient balance at [Fuji block-explorer](https://cchain.explorer.avax-test.network/). You can fund your address from the Avalanche testnet [faucet](https://faucet.avax-test.network/).

2022-02-16 08:03 UTC, hyp3r5pace commented
Hii @pyr0gan, We made the changes as requested!

2022-02-17 06:07 UTC, pyr0gan approved these changes
This is going to sound really picky, but the markdown parser is unforgiving of extra linebreaks and whitespace. Anything inside of a hint tag needs to be on a single line (no extra linebreaks without using the markdown `\` linebreak syntax).

So they should all look like this:

>```text
>{% hint style="tip" %}
>Make sure the Solidity compiler version being used in Remix matches the version used at the beginning of the smart contract.
>{% endhint %}
>```

Fix that, and we should be OK to merge 😄

2022-02-17 07:31 UTC, hyp3r5pace commented
> This is going to sound really picky, but the markdown parser is unforgiving of extra linebreaks and whitespace. Anything inside of a hint tag needs to be on a single line (no extra linebreaks without using the markdown `\` linebreak syntax).
> 
> So they should all look like this:
> 
> > ```
> > {% hint style="tip" %}
> > Make sure the Solidity compiler version being used in Remix matches the version used at the beginning of the smart contract.
> > {% endhint %}
> > ```
> 
> Fix that, and we should be OK to merge 😄

Hiii @pyr0gan We made the changes as requested. 👍🏻

2022-02-17 17:45 UTC, merged