Build-a-Crowdfunding-dApp-on-NEAR
figment-networks/learn-tutorials pull request #367
Opened 2022-02-08 01:37 UTC by uma-victor1

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request", make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8) and reviewed the [Sample Tutorial Structure](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d). 

Please confirm the following before submitting your tutorial for review - 

- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [x] The title of the Pull Request matches the title of my tutorial.
- [x] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [x] I've [proofread the tutorial](https://grammarly.com) for spelling and grammar mistakes.
- [x] I've run a linter & prettifier to format my code blocks.
- [x] I've thoroughly explained the code, with inline code comments and text explanations.
- [x] I've run the tutorial to test it and the code works.

**NOTE**: We cannot review your Pull Request if it does not meet the standard outlined above.

2022-02-09 13:22 UTC, uma-victor1 commented
Hi @yash-sharma1, when will the article be reviewed?

2022-02-15 11:57 UTC, yash-sharma1 commented
> Hi @yash-sharma1, when will the article be reviewed?

Hey, @uma-victor1 I'm going to start the initial review of the tutorial and will let you know about all the changes required.

2022-02-15 13:00 UTC, yash-sharma1 commented on near/Build_a_Crowdfunding_dApp_on_NEAR .md
> +Yay!. We have concluded the tutorial and you can find the source code [here](https://github.com/uma-victor1/Crowdfunding-dApp).
Before this can you please include a gif/video which covers the demo walkthrough of the platform, it'll be interesting to see the final result.

2022-02-15 13:02 UTC, yash-sharma1 commented on near/Build_a_Crowdfunding_dApp_on_NEAR .md
> +## Conclusion
After conclusion, make sure to include the "What's next?" step where you can give some ides to brainstorm & implement them in the existing tutorial to all the devs who will go through tutorial. You can mention what other features can be included in this

2022-02-15 13:04 UTC, yash-sharma1 commented on near/Build_a_Crowdfunding_dApp_on_NEAR .md
> +# Build a Crowdfunding dApp on NEAR.
Please remove the tutorial heading becuase we'll add the tutroial name mnually while adding the tutorial to learn site.

2022-02-15 13:06 UTC, yash-sharma1 commented on near/Build_a_Crowdfunding_dApp_on_NEAR .md
> +## Introduction
Across the tutorial you've used the H2 heading (##) for all the main section headings so please update them with H1 (#) and keep the sub-headings in H2 (##)

2022-02-15 13:11 UTC, yash-sharma1 commented
Meanwhile, @pyr0gan can take another look at this tutorial and let @uma-victor1 know if any other changes are required.

2022-02-15 15:46 UTC, uma-victor1 commented on near/Build_a_Crowdfunding_dApp_on_NEAR .md
> +Yay!. We have concluded the tutorial and you can find the source code [here](https://github.com/uma-victor1/Crowdfunding-dApp).
@yash-sharma1 can i link to a video giving a walkthrough of the dApp?

2022-02-15 16:00 UTC, uma-victor1 commented
@yash-sharma1, I have made the changes in the new commit. I'll be waiting for @pyr0gan to also take a look.

2022-02-15 19:28 UTC, pyr0gan requested changes
Hi @uma-victor1 👋 

There are a number of fixes to be made here, mostly in the category of code blocks and image links. Please have a look over my comments and make the necessary changes. If you have any questions about how to apply code blocks using backticks (\```) or how to get the images uploaded and linked properly, please tag me in a reply and I will assist you 😄

2022-02-15 19:28 UTC, pyr0gan commented on near/Build_a_Crowdfunding_dApp_on_NEAR .md
>  ![](https://paper-attachments.dropbox.com/s_6663B3E85151DBD5BD66114327FA68CBB8E9D8C0AC631CAC16FA01B63E05A7E0_1643848112786_filestructure.png)
It's better to upload your images to the `assets` directory and include them in the Pull Request. Then you'll also need to update the link format to:

\![Image Description]\(https://raw.githubusercontent.com/figment-networks/learn-tutorials/master/assets/filestructure.png?raw=true)

The thing to remember here is that you're pointing to the repository `learn-tutorials`, the branch `master` and the `assets` directory. Using the `raw.githubusercontent.com` domain and `?raw=true` will ensure that your images are correctly displayed 😄

2022-02-15 19:28 UTC, pyr0gan commented on near/Build_a_Crowdfunding_dApp_on_NEAR .md
>  1. Create a crowdfunding project - To do this we will need a `add_crowdfund` function, that when invoked will create a new crowdfunding project and add it to our array of crowdfunds.
On line 84 where your code block begins and line 139 where it ends, please remember to use the code block syntax:

\```rust
// utils.rs
    use near_sdk::{
        env,
        PromiseResult,
};

// ... the rest of the code ...

\```

The triple backticks including the name of the programming language to perform syntax highlighting on the code to begin the code block (\```rust) and three backticks to end the code block (\```).

**IMPORTANT** : You will need to do this for all code blocks in the document for it to render properly on the Learn site!

2022-02-15 19:28 UTC, pyr0gan commented on near/Build_a_Crowdfunding_dApp_on_NEAR .md
> +## The `**add_crowdfund**` function
There can be no extra Markdown formatting in a heading, or it will not render properly. Please use:

> \## The add_crowdfund function

Please refer to the [sample tutorial](https://www.notion.so/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) for more information regarding section headings 😄

2022-02-15 19:28 UTC, pyr0gan commented on near/Build_a_Crowdfunding_dApp_on_NEAR .md
>  **Login with** `**near-cli**`
Be careful with Markdown formatting 😄 

This should be written as \*\*Login with \`near-cli\`** to have the intended effect of "**Login with `near-cli`**" (the **bold** formatting does not need to be applied inside of the preformatted text, only surrounding the text you want in **bold**) 👍

2022-02-15 19:28 UTC, pyr0gan commented on near/Build_a_Crowdfunding_dApp_on_NEAR .md
>      near call crowdfunddapp.umavictor.testnet add_vote '{"id":0}' --accountId umavictor.testnet
Even single line terminal commands like this can benefit from being shown in a code block, but remember to use \```text for syntax highlighting:

```text
near call crowdfunddapp.umavictor.testnet add_vote '{"id":0}' --accountId umavictor.testnet
```

2022-02-15 19:28 UTC, pyr0gan commented on near/Build_a_Crowdfunding_dApp_on_NEAR .md
>  ![](https://paper-attachments.dropbox.com/s_6663B3E85151DBD5BD66114327FA68CBB8E9D8C0AC631CAC16FA01B63E05A7E0_1644096453517_addvote.png)
See the previous comment about image links and using the `raw.githubusercontent.com` domain. You will need to add your images to the Pull Request by adding them to the `assets` directory and also fix all the image links 👍

2022-02-15 22:35 UTC, uma-victor1 commented
@pyr0gan, I have made the requested changes. I also linked a video walkthrough for the dApp. You can take a look.

2022-02-17 06:02 UTC, pyr0gan approved these changes

2022-02-17 06:02 UTC, pyr0gan commented
@yash-sharma1 Are you satisfied with the changes? 😄

2022-02-17 06:13 UTC, yash-sharma1 commented
> @yash-sharma1 Are you satisfied with the changes? 😄

Let me take a look at the changes now :)

2022-02-17 06:18 UTC, yash-sharma1 commented on near/Build_a_Crowdfunding_dApp_on_NEAR .md
> +In this tutorial, we will build a crowdfunding dApp on the NEAR blockchain. Our smart contract will be written in Rust and our frontend will be written in React. In the dApp we built, the user can:
@uma-victor1 Only the last line of the sentence was needed to be updated not the whole intro. Can you please add - "In this tutorial, we will build a crowdfunding dApp on the NEAR blockchain. Our smart contract will be written in Rust and our frontend will be written in React." before moving to bullet points

2022-02-17 06:32 UTC, yash-sharma1 commented
@uma-victor1 looks good to me, just one small change required in the introduction section for which I left the comment.

2022-02-17 06:45 UTC, uma-victor1 commented
@yash-sharma1, I have added back the introduction. Everything should be fine now.

2022-02-17 06:49 UTC, yash-sharma1 approved these changes

2022-02-17 06:51 UTC, yash-sharma1 commented
@pyr0gan I've approved the requested changes, you can merge and add it to learn if it's good to go from your end too. 
Thanks, @uma-victor1 for the quick fix, appreciate it.

2022-02-17 17:44 UTC, merged